---
- hosts: localhost
  gather_facts: false 
  tasks:
    - name: Print Hi, Ken!
      ansible.builtin.debug:
        msg: "Hi, {{ my_variable | default('Ken') }}!"
      vars: 
        my_variable: 'Barbie'
