---
- name: Add new user
  hosts: all
  become: true 
  gather_facts: false 

  tasks:
    - name: Create a new user
      ansible.builtin.user:
        name: jsmith
        group: root
        create_home: yes

    - name: Add SSH key for jsmith
      tags: always
      ansible.posix.authorized_key: 
        user: jsmith
        key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCjTFIWgh8YLPhjiE2e+bIxUhiZeBB/+/tulNtXW8w986whRq4USpaBPfwbwP+BH0v6KDZ/RIDsqioUSNFGeKVsaBFsOWAQ26sgWb/njWyQnQ3tcFj2KF4tFijhUb8xRQRvRCUQ02a2PNO4DAtVagbTdRn+d3Q4P0tVzjFqW+vSZnzoB0fTbSwxqqyhkyiL4Jc0xkuWr5HsAbuPFLlrVJiikTR/q/1vRWVjj6tPugtmeVjHnzSGBZf3+E/B7amBCbTPajhkfTSAPI40Kom4ioo12ACGoQCQj7kSRK0khhIgaiLwqa1oV1fzgOgDfgxxTvsXN2v7BhpN0Wi5cFXQOj3lwUBEeZpXNxPBtvKtZSXktQjiPP5O2jckypw/6H8cXCcYVcu4lSZc6sD4zXRQjznhOTukcW7RFf2xrmbw0qC3ZHcj8VH1IdnPxEm0Y9h8qJiiHGuTJWX/C4s/TWGJlVB0ilpbjjJR2U5sieJ48XjL+J+iMOffuHiaLJ7hpQnNoHZuVOtI2PqM9QAqkhhNjvko0wmrAyJrZlVmZCkJ05JcsthYG+OyWD1SbODgx54TNM72BI9rzEyNX1McBA5qHeoxE7G5Ufe1PqaHeRyk8fidaJnTrmbES8jrKLh8Z6v87WlYeuWSmt1kk5u3o0xYZrwqyaH4sZFRIqtgsdgmVIOAsQ== jdoe@f38s1

    - name: Add sudoers file for jsmith
      tags: always 
      ansible.builtin.copy:
        src: sudoer_jsmith
        dest: /etc/sudoers.d/jsmith
        owner: root
        group: root
        mode: '0440'
