---
- name: Install SFTP server on Fedora/CentOS/Red Hat/EC2 Linux
  hosts: all
  become: true 
  vars:
    sftp_user: stfpuser  
    sftp_dir: /var/sftp
    sftp_data_dir: /var/sftp/sftpdata
  
  tasks:
    - name: Add a new user and set the password
      ansible.builtin.user:
        name: "{{ sftp_user }}"
        password: "{{ 'B3llaVita!@' | password_hash('sha512') }}"
        update_password: always
    
    - name: Create the SFTP Directory
      ansible.builtin.file:
        path: "{{ sftp_dir }}"
        state: directory

    - name: Create the SFTP Data Directory
      ansible.builtin.file:
        path: "{{ sftp_data_dir }}"
        state: directory
    
    - name: Set Ownership of SFTP Directories
      ansible.builtin.file:
        path: "{{ item.path }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      loop:
        - { path: "{{ sftp_dir }}", owner: "root", group: "root", mode: "0755" }
        - { path: "{{ sftp_data_dir }}", owner: "{{ sftp_user }}", group: "{{ sftp_user }}", mode: "0700" }

    - name: Copy sshd_config.j2 file from current working directory to /etc/ssh/
      ansible.builtin.copy:
        src: sshd_config.j2
        dest: /etc/ssh/sshd_config  # Correct path
        mode: '0600'
        owner: root
        group: root
    
    - name: Modify sshd_config file
      ansible.builtin.template:
        src: sshd_config.j2
        dest: /etc/ssh/sshd_config  # Correct path
        owner: root
        group: root
        mode: '0600'
      notify: restart sshd
    
    - name: Check sshd_config file syntax
      ansible.builtin.command: sshd -t
      register: sshd_config_syntax
      changed_when: false  # This task is for validation, should not be marked as changed

  handlers:
    - name: restart sshd
      ansible.builtin.systemd:
        name: sshd
        state: restarted
      when: sshd_config_syntax.rc == 0

