---
- hosts: all
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_distribution=='Ubuntu'

    - name: Install Apache2 package
      ansible.builtin.apt:
        name: apache2
        state: present
      when: ansible_distribution=='Ubuntu'

    - name: Ensure Apache2 service is running
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_distribution=='Ubuntu'
