---
- name: Updating Fedora Servers
  hosts: all
  become: true 

  tasks:
    - name: Update package cache
      ansible.builtin.dnf:
        update_cache: yes 
      when: ansible_distribution=='Fedora' and ansible_distribution_major_version== '40'

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_distribution=='Ubuntu' and ansible_distribution_major_version== '24'