---
- name: Enable httpd on Fedora Servers
  hosts: all
  become: true
  tasks:

    - name: Gather facts about the system
      ansible.builtin.setup:

    - name: Ensure httpd service is running
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_facts['distribution'] == 'Fedora'

    - name: Open HTTP port 80 on Fedora
      firewalld:
        service: http
        permanent: true
        state: enabled
      when: ansible_facts['distribution'] == 'Fedora'

    - name: Reload firewall rules for new service to kick-in
      ansible.builtin.command:
        cmd: firewall-cmd --reload
      when: ansible_facts['distribution'] == 'Fedora'
