---
- name: Install useful Linux tools
  hosts: db_server
  become: true
  collections:
    - ansible.builtin

  pre_tasks:
    - name: Install updates (ubuntu)
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    
    - name: Install updates (Fedora)
      dnf:
        update_only: yes 
        update_cache: yes 
      when: ansible_distribution == "Fedora"

- name: Install useful Linux tools
  hosts: db_server
  become: true

  tasks:
    - name: Install htop, nmon, iftop packages
      package:
        name: ['htop', 'nmon', 'iftop']
        state: latest

    - name: Install MariaDB package (Ubuntu)
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"
    
    - name: Install MariaDB packahe (Fedora)
      dnf:
        name: ['mariadb', 'mariadb-server']
        state: latest
      when: ansible_distribution == "Fedora"