---
- hosts: all
  become: true 
  gather_facts: false

  tasks:
    - name: Update repository index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Apache2 package
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Ensure Apache2 service is running
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes
