---
- name: Add Updates to Playbook
  hosts: all
  become: true
  collections:
    - ansible.builtin

  tasks:
    - name: Install updates (Ubuntu)
      tags: always
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      when: ansible_facts['distribution'] == "Ubuntu"
    
    - name: Install updates (Fedora)
      tags: always
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: yes
      when: ansible_facts['distribution'] == "Fedora"

- name: Install Apache and HTTPD Services
  hosts: linux
  become: true

  tasks:
    - name: Install apache2 & PHP packages for Ubuntu
      tags: ubuntu,apache
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_facts['distribution'] == "Ubuntu"
    
    - name: Install httpd & PHP packages for Fedora/CentOS
      tags: fedora,httpd
      ansible.builtin.dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_facts['distribution'] == "Fedora"
