---
- name: Install Terraform
  hosts: f38c1
  become: true
  gather_facts: false
  collections:
    - ansible.builtin

  tasks:
    - name: Install unzip package
      ansible.builtin.package:
        name: unzip
        state: present

    - name: Download and Install Terraform
      ansible.builtin.unarchive:
        src: https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_arm64.zip
        dest: /usr/local/bin
        remote_src: yes
        owner: root
        group: root
        mode: '0755'
